spring:
  datasource:
    username: order
    password: order
    url: jdbc:mysql://localhost:3306/order
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        order-created:
          destination: order-created
          contentType: application/json

